#!/usr/bin/env sh

newpkg () {
    [ -z "$1" ] && { printf %s\\n 'usage: newpkg pkgname' ; return 1; }
    PKGNAME="$1"
    git clone "ssh://aur@aur.archlinux.org/${PKGNAME}.git"                          && \
    git submodule add -f "ssh://aur@aur.archlinux.org/${PKGNAME}.git" "$PKGNAME"    && \
    sed "s/AUR_PKGNAME/${PKGNAME}/g" PKGBUILD-base > "${PKGNAME}/PKGBUILD"          && \
    cd "$PKGNAME"
}

mksrcinfo () {
    [ -f "PKGBUILD" ] || { printf %s\\n 'file PKGBUILD not found' ; return 1; }
    makepkg --printsrcinfo > .SRCINFO && \
        printf %s\\n '.SRCINFO successfully regenerated.'
}

alias ep='$EDITOR PKGBUILD && mksrcinfo'

# just tar it since we want devel process to be faster
alias mkpkg="PKGEXT='.pkg.tar' makepkg -cs"
alias ipkg='sudo pacman -U *.pkg.tar'
